{% set version = "0.3.35" %}

package:
  name: langchain-openai
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/langchain-openai/langchain_openai-{{ version }}.tar.gz
  sha256: fa985fd041c3809da256a040c98e8a43e91c6d165b96dcfeb770d8bd457bf76f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - langchain-core >=0.3.78,<1.0.0
    - openai >=1.104.2,<3.0.0
    - tiktoken >=0.7.0,<1.0.0

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - langchain_openai

about:
  home: https://github.com/langchain-ai/langchain/tree/master/libs/partners/openai
  license: Apache-2.0
  license_file: LICENSE
  summary: LangChain integrations for OpenAI through their openai SDK

extra:
  recipe-maintainers:
    - jan-janssen
    - pavelzw
    - raybellwaves
