{% set version = "0.1.3" %}

package:
  name: langchain-openai
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/langchain-openai/langchain_openai-{{ version }}.tar.gz
  sha256: 7f6e377d6bf88d6c2b1969fe5eecc1326271757512739e2f17c855cd7af53345

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0
    - langchain-core >=0.1.42,<0.2.0
    - openai >=1.10.0,<2.0.0
    - tiktoken >=0.5.2,<1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - langchain_openai

about:
  home: https://github.com/langchain-ai/langchain/tree/master/libs/partners/openai
  license: Apache-2.0
  license_file: LICENSE
  summary: LangChain integrations for OpenAI through their openai SDK

extra:
  recipe-maintainers:
    - pavelzw
    - raybellwaves
