{% set version = "0.3.29" %}

package:
  name: langchain-openai
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/langchain-openai/langchain_openai-{{ version }}.tar.gz
  sha256: 83a0455f8ce874aa1806131ca3b4db08e482be037b7457a9b3ca21a213d2ab47

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - langchain-core <1.0.0,>=0.3.74
    - openai <2.0.0,>=1.86.0
    - tiktoken <1,>=0.7

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - langchain_openai

about:
  home: https://github.com/langchain-ai/langchain/tree/master/libs/partners/openai
  license: Apache-2.0
  license_file: LICENSE
  summary: LangChain integrations for OpenAI through their openai SDK

extra:
  recipe-maintainers:
    - jan-janssen
    - pavelzw
    - raybellwaves
