{% set version = "0.2.2" %}

package:
  name: langchain-openai
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/langchain-openai/langchain_openai-{{ version }}.tar.gz
  sha256: 9ae8e2ec7d1ca84fd3bfa82186724528d68e1510a1dc9cdf617a7c669b7a7768

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8
    - langchain-core <0.4,>=0.3
    - openai >=1.40.0,<2.0.0
    - tiktoken >=0.7,<1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - langchain_openai

about:
  home: https://github.com/langchain-ai/langchain/tree/master/libs/partners/openai
  license: Apache-2.0
  license_file: LICENSE
  summary: LangChain integrations for OpenAI through their openai SDK

extra:
  recipe-maintainers:
    - jan-janssen
    - pavelzw
    - raybellwaves
